name        = "API-Ref Hugo Theme"
license     = "MIT"
description = "API reference monospace theme"
homepage    = "https://github.com/YouSysAdmin/hugo-theme-api-ref"
tags        = ["docs", "documentation", "dark", "light", "api", "changelog"]
features    = ["sidebar", "toc", "changelog", "multiple versions"]
min_version = "0.150.0"

[author]
  name = "YouSysAdmin"
